#%RAML 1.0
---
title: Individuals Details
version: P1.0
protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/
mediaType: [ application/json, application/hal+json ]

documentation:
 - title: Overview
   content: !include docs/overview.md
 - title: Versioning
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/versioning.md
 - title: Errors
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/errors.md
 - title: Testing
   content: !include docs/testing.md

uses:
  sec: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/securitySchemes.raml
  headers: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/headers.raml
  annotations: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/annotations.raml
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

/hello-world:
  get:
    displayName: Hello World
    description: An endpoint that returns hello world
    is: [headers.acceptHeader]
    responses:
      200:
        description: Return hello world
        body:
          application/json:
            example: "\"Hello World\""


/contact-details:
  get:
    displayName: Contact Details
    description: A placeholder endpoint for contact details that will throw an exception
    is: [headers.acceptHeader]
    responses:
      500:
        description: Throws an exception
        body:
            application/json:
                "\"Not yet implemented\""

/:
   get:
     displayName: Root
     description: A placeholder endpoint for root that will throw an exception
     is: [headers.acceptHeader]
     responses:
       500:
         description: Throws an exception
         body:
             application/json:
                 "\"Not yet implemented\""