#%RAML 1.0
---
title: Individuals Details
version: P1.0
protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/
mediaType: [ application/json, application/hal+json ]

documentation:
 - title: Overview
   content: !include docs/overview.md
 - title: Versioning
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/versioning.md
 - title: Errors
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/errors.md
 - title: Testing
   content: !include docs/testing.md

uses:
  sec: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/securitySchemes.raml
  headers: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/headers.raml
  annotations: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/annotations.raml
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml
/individuals/details:
    /hello-world:
      get:
        displayName: Hello World
        description: An endpoint that returns hello world
        is: [headers.acceptHeader]
        responses:
          200:
            description: Return hello world
            body:
              application/json:
                example: "\"Hello World\""

    /:
      get:
        displayName: Root
        description: Use this endpoint to get a list of all available endpoints for Individuals Details.
        is: [headers.acceptHeader]
        (annotations.sandboxData): !include sandbox/root.md
        headers:
          Authorization:
            description: An OAuth 2.0 Bearer Token with the scopes you have been assigned.
            type: string
            required: true
            example: Bearer <BEARER_TOKEN>
        queryParameters:
          matchId:
            description: A short-lived UUID, typically valid for several hours. Generated through the Individuals Matching API.
            type: string
            example: 57072660-1df9-4aeb-b4ea-cd2d7f96e430
        responses:
          200:
            description: Throws an exception
            body:
                application/json:
                    example: !include examples/root-response.json
                    type: !include schemas/root-response.json
          400:
            body:
              application/json:
                type: types.errorResponse
                examples:
                  BadRequest:
                    description: Invalid request
                    value:
                      code: INVALID_REQUEST
          404:
            body:
              application/json:
                type: types.errorResponse
                examples:
                  NotFound:
                    description: Not found
                    value:
                      code: NOT_FOUND

    /contact-details:
      get:
        displayName: Contact Details
        description: Use this endpoint to get an individual’s contact details.
        is: [headers.acceptHeader]
        (annotations.sandboxData): !include sandbox/contact-details.md
        headers:
          Authorization:
            description: An OAuth 2.0 Bearer Token with the scopes you have been assigned.
            type: string
            required: true
            example: Bearer <BEARER_TOKEN>
        queryParameters:
          matchId:
            description: A short-lived UUID, typically valid for several hours. Generated through the Individuals Matching API.
            type: string
            example: 57072660-1df9-4aeb-b4ea-cd2d7f96e430
        responses:
          200:
            description: Use this endpoint to get an individual’s contact details
            body:
                application/json:
                  example: !include examples/contact-details-response.json
                  type: !include schemas/contact-details-response.json
          400:
            body:
              application/json:
                type: types.errorResponse
                examples:
                  BadRequest:
                    description: Invalid request
                    value:
                      code: INVALID_REQUEST
          404:
            body:
              application/json:
                type: types.errorResponse
                examples:
                  NotFound:
                    description: Not found
                    value:
                      code: NOT_FOUND

    /addresses:
      get:
        displayName: Addresses
        description: Use this endpoint to get a list of all available endpoints for Individuals Details.
        is: [headers.acceptHeader]
        (annotations.sandboxData): !include sandbox/addresses.md
        headers:
          Authorization:
            description: An OAuth 2.0 Bearer Token with the scopes you have been assigned.
            type: string
            required: true
            example: Bearer <BEARER_TOKEN>
        queryParameters:
          matchId:
            description: A short-lived UUID, typically valid for several hours. Generated through the Individuals Matching API.
            type: string
            example: 57072660-1df9-4aeb-b4ea-cd2d7f96e430
        responses:
          200:
            description: Use this endpoint to get an individual’s addresses
            body:
                application/json:
                  example: !include examples/addresses-response.json
                  type: !include schemas/addresses-response.json
          400:
            body:
              application/json:
                type: types.errorResponse
                examples:
                  BadRequest:
                    description: Invalid request
                    value:
                      code: INVALID_REQUEST
          404:
            body:
              application/json:
                type: types.errorResponse
                examples:
                  NotFound:
                    description: Not found
                    value:
                      code: NOT_FOUND

